### PR TITLE
Admin menu and User agenda view

### PR DESCRIPTION
**Pull request by davidwessman**
Adding an administrative menu in the main menu

Adding the Agenda to starting page.
Some parts of #52 and #51.

### CODE REVIEW

**Comment by navro** [comment]
This looks really nice on the front page! :smile:

We need to think about what to do with child objects. For example, if we open "§13.1 Propositioner/First" it does not show up in the list (and the parent is marked as cloed).

**Comment by davidwessman** [comment]
What if we check if a agenda has `Current` children?

**Comment by navro** [comment]
That would work

**Comment by davidwessman** [comment]
Check this out, I think it works out 😄 
Could use some specs for the current agenda.

**Comment by navro** [comment]
Looks good now!
+1

**Pull request merged**
